### PR TITLE
bump: github.com/quic-go/quic-go to v0.53.0

### LINKED ISSUE #311: caddy-l4 doesn't build with latest caddy `master` branch
Hello, and thanks for maintaining caddy-l4.

Just want to let you know that caddy-l4 no longer builds with https://github.com/caddyserver/caddy/commit/11c6daecd7663bd625ec823f585a1c502468b1e7 (or later).  The linked commit upgrades quic-go to version [0.53.0](https://github.com/quic-go/quic-go/releases/tag/v0.53.0) which makes some backwards-incompatible API changes.

``` shell
xcaddy build 11c6daecd7663bd625ec823f585a1c502468b1e7 \
  --with=github.com/mholt/caddy-l4@4d3c80e89c5f80438a3e048a410d5543ff5fb9f4
```

``` text
<snip>
../../go/pkg/mod/github.com/mholt/caddy-l4@v0.0.0-20250530154005-4d3c80e89c5f/modules/l4quic/matcher.go:146:17: undefined: quic.EarlyConnection
<snip>
```

The previous Caddy commit works fine:

```
xcaddy build 3b4d966fba069e9895980dbbf05f84bf818968ba \
  --with=github.com/mholt/caddy-l4@4d3c80e89c5f80438a3e048a410d5543ff5fb9f4
```

### PR DESCRIPTION
**Pull request by IceCodeNew**
fix #311

### CODE REVIEW

**Comment by mholt** [comment]
Thanks for the PR -- looks like the tests might also need to be updated in order to be passing. I don't have a chance to look into it at the moment but we could probably merge this when they pass.

**Comment by IceCodeNew** [comment]
I will fix the test this weekend since I’m on holiday. 😊

**Comment by mholt** [comment]
Yes, a timeout during matching is a concerning test failure.

**Comment by IceCodeNew** [comment]
I need some help here.
It seems that test cases with ALPN specified (m2, m3) will somehow fail at https://github.com/mholt/caddy-l4/blob/77e8af43042db2d78b5b2f3097861efeb0a8bb0b/modules/l4quic/matcher.go#L147
I tried to put the qListener.Accept() function in a loop, as the documents suggested, but no luck here.

**Comment by marten-seemann** [comment]
You might want to try updating in smaller increments. You're going from v0.44.0 to v0.53.0. **A lot** has changed between these releases, and figuring out which release causes the failure would help us narrow down what could be going wrong here.

**Comment by manselmi** [comment]
FYI Caddy has since bumped quic-go to [v0.54.0](https://github.com/caddyserver/caddy/pull/7138).

**Comment by manselmi** [comment]
Hi, how has this been going?

**Comment by jurekl** [comment]
I don't think it bothers anyone too much...

**Comment by marten-seemann** [comment]
@manselmi This is an open source project, why don’t you contribute the respective code?

**Comment by manselmi** [comment]
@marten-seemann I would if I knew how. Not a Go dev.

**Comment by vnxme** [comment]
Hi there, I've investigated the issue with `l4quic` matcher and `quic-go` dependency, and it has 2 implications:
1. The matcher has a bug when it comes to the moment it tries to close quic.EarlyListener which makes the tests fail if we upgrade dependenices (go v1.24, caddyserver/caddy v2.10.0, quic-go v0.51.1). I will submit a fix and an upgrade PR soon.
2. The quic-go has its syntax changed from v0.51.1 to v0.54.0: `quic.EarlyListener.Accept` now returns `*quic.Conn` instead of `quic.EarlyConnection`. However, we can't update the matcher and modify `caddy-l4` go.mod to use the newest `quic-go` unless the mainline Caddy requiring this `quic-go` (v0.54.0) is released (since it uses quic.EarlyConnection as well). This prevents automatic builds with Caddy master.

**Comment by vnxme** [comment]
Actually, we can resolve the issue with building against Caddy master by means of referring to a pseudo-version. Credits to @IceCodeNew for this brilliant idea show in this PR.
