### ISSUE TITLE
caddy-l4 doesn't build with latest caddy `master` branch

### ISSUE THREAD

**Issue by manselmi** [mholt/caddy-l4#311]
Hello, and thanks for maintaining caddy-l4.

Just want to let you know that caddy-l4 no longer builds with https://github.com/caddyserver/caddy/commit/11c6daecd7663bd625ec823f585a1c502468b1e7 (or later).  The linked commit upgrades quic-go to version [0.53.0](https://github.com/quic-go/quic-go/releases/tag/v0.53.0) which makes some backwards-incompatible API changes.

``` shell
xcaddy build 11c6daecd7663bd625ec823f585a1c502468b1e7 \
  --with=github.com/mholt/caddy-l4@4d3c80e89c5f80438a3e048a410d5543ff5fb9f4
```

``` text
<snip>
../../go/pkg/mod/github.com/mholt/caddy-l4@v0.0.0-20250530154005-4d3c80e89c5f/modules/l4quic/matcher.go:146:17: undefined: quic.EarlyConnection
<snip>
```

The previous Caddy commit works fine:

```
xcaddy build 3b4d966fba069e9895980dbbf05f84bf818968ba \
  --with=github.com/mholt/caddy-l4@4d3c80e89c5f80438a3e048a410d5543ff5fb9f4
```

**Comment by manselmi** [comment]
Looks like this will be fixed by #316. Thanks @vnxme!
